### ISSUE TITLE
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Windows Kits\10\include'

### ISSUE THREAD

**Issue by AntonVonDelta** [soup-build/soup#285]
**Describe the bug**
`swhere` throws the exception:
```
Local User Config file does not exist
No existing local user config.
C:/Windows/System32/where.exe dotnet
Using DotNet: C:/Program Files/dotnet/dotnet.exe
Find DotNet SDK Versions
C:/Program Files/dotnet/dotnet.exe --list-sdks
Found SDK: 9.0.101 C:/Program Files/dotnet/sdk
Find DotNet Runtime Versions
C:/Program Files/dotnet/dotnet.exe --list-runtimes
Found Runtime: Microsoft.AspNetCore.App 6.0.36 C:/Program Files/dotnet/shared/Microsoft.AspNetCore.App
Found Runtime: Microsoft.AspNetCore.App 8.0.11 C:/Program Files/dotnet/shared/Microsoft.AspNetCore.App
Found Runtime: Microsoft.AspNetCore.App 9.0.0 C:/Program Files/dotnet/shared/Microsoft.AspNetCore.App
Found Runtime: Microsoft.NETCore.App 6.0.36 C:/Program Files/dotnet/shared/Microsoft.NETCore.App
Found Runtime: Microsoft.NETCore.App 8.0.11 C:/Program Files/dotnet/shared/Microsoft.NETCore.App
Found Runtime: Microsoft.NETCore.App 9.0.0 C:/Program Files/dotnet/shared/Microsoft.NETCore.App
Found Runtime: Microsoft.WindowsDesktop.App 6.0.36 C:/Program Files/dotnet/shared/Microsoft.WindowsDesktop.App
Found Runtime: Microsoft.WindowsDesktop.App 8.0.11 C:/Program Files/dotnet/shared/Microsoft.WindowsDesktop.App
Found Runtime: Microsoft.WindowsDesktop.App 9.0.0 C:/Program Files/dotnet/shared/Microsoft.WindowsDesktop.App
FindDotNetPackVersions: C:/Program Files/dotnet/packs/Microsoft.NETCore.App.Ref
C:/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
Using VS Installation: D:/Programs/Visual Studio
Using VC Version: 14.42.34433
FindNewestWindows10KitVersion: C:/Program Files (x86)/Windows Kits/10/
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Windows Kits\10\include'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String, Boolean )
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String, Boolean, EnumerationOptions )
   at System.IO.Enumeration.FileSystemEnumerable`1.DelegateEnumerator..ctor(FileSystemEnumerable`1, Boolean)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String, FindTransform, EnumerationOptions, Boolean)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String, FindTransform , EnumerationOptions )
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String, String, EnumerationOptions)
   at System.IO.Directory.InternalEnumeratePaths(String, String, SearchTarget, EnumerationOptions)
   at System.IO.Directory.EnumerateDirectories(String, String, EnumerationOptions)
   at System.IO.Directory.EnumerateDirectories(String)
   at Opal.System.RuntimeFileSystem.GetChildDirectories(Path)
   at Soup.Build.Discover.WindowsSDKUtilities.FindNewestWindows10KitVersion(Path)
   at Soup.Build.Discover.WindowsSDKUtilities.FindWindows10Kit()
   at Soup.Build.Discover.SwhereManager.DiscoverWindowsPlatformAsync(Boolean, LocalUserConfig)
   at Soup.Build.Discover.SwhereManager.DiscoverAsync(Boolean)
   at Soup.Build.Discover.Program.Main(String[])
   at Soup.Build.Discover.Program.<Main>(String[] )
```

The error happens because I have installed Visual Studio together with the Windows Kit on D:\ drive. I can't move it on C:\ drive because of space requirements. I file this as a bug because I think the path shouldn't be hardcoded (https://github.com/soup-build/soup/blob/d165cc575bd3176097770ee51461c8eabc978351/Source/GenerateSharp/Swhere/WindowsSDKUtilities.cs#L16) but inferred from registry for Windows platforms.

**To Reproduce**
1. Install Visual Studio to a custom folder
3. `winget install SoupBuild.Soup`
4. `swhere`
5. See error

**Expected behavior**
Path for `Windows Kits` can be taken from registry. I found what seems to be the key here: `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows\v10.0`

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by mwasplund** [comment]
@AntonVonDelta thank's for taking the time to submit the issue. I submitted a PR to use the registry to lookup the install folder. I am on vacation right now, so I do not have a fresh windows install to test custom installs on. Ill setup a VM when I get home and test this change for real.
